sudo: false

language: python

python:
  - 3.6

install:
  - pip install codecov
  - pip install websockets

script:
  - coverage run tests/test_server.py
  - coverage run tests/test_database.py

after_success:
  - codecov