sudo: false

language: python

python:
  - 3.6

install:
  - pip install ./requirements.txt
  - pip install codecov

script:
  - python tests/test_server.py
  - python tests/test_database.py
  - coverage run tests/test_server.py
  - coverage run tests/test_database.py

after_success:
  - codecov