sudo: false

language: python

python:
  - 3.6

before_script:
- pip install coveralls coverage setuptools

install:
  - pip install -r requirements.txt

script:
- pytest tests/

after_success:
- coveralls