sudo: false

language: python

python:
  - 3.6

before_script:
- pip install coveralls coverage setuptools nose

install:
  - pip install -r requirements.txt

script:
- nosetests tests/ --with-coverage

after_success:
- coveralls