sudo: false

language: python

python:
  - 3.6

before_script:
- pip install coveralls coverage setuptools

install:
  - pip install -r requirements.txt

script:
- python -m pytest ./tests/*
- coverage run --source tests -m unittest discover
- coverage report -m
- coverage run --source Server -m unittest discover
- coverage report -m
- coverage run --source ConfigManager -m unittest discover
- coverage report -m

after_success:
- coveralls