sudo: false

language: python

python:
  - 3.6

install:
  - pip install -r requirements.txt
  - pip install codecov

script:
- python tests/*.py
- python Server/*.py
- python ConfigManager/*.py
- coverage run tests/*.py
- coverage run Server/*.py
- coverage run ConfigManager/*.py

after_success:
  - codecov