sudo: false

language: python

python:
  - 3.6

before_script:
- pip install coveralls coverage setuptools nose

install:
  - pip install -r requirements.txt

script:
- python tests/*.py
- python Server/*.py
- python ConfigManager/*.py
- nosetests --with-coverage -w ./

after_success:
- coveralls